source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

workspace 'Cocoapods-Latest.xcworkspace'

target 'Swift-iOS' do
	platform :ios, 13
	project 'Swift.xcodeproj'
	pod 'PusherSwift', :path => '../../'
end

target 'Swift-macOS' do
	platform :osx, 10.15
	project 'Swift.xcodeproj'
	pod 'PusherSwift', :path => '../../'
end

target 'ObjectiveC-iOS' do
	platform :ios, 13
	project 'ObjectiveC.xcodeproj'
	pod 'PusherSwift', :path => '../../'
end

target 'ObjectiveC-macOS' do
	platform :osx, 10.15
	project 'ObjectiveC.xcodeproj'
	pod 'PusherSwift', :path => '../../'
end